path: "tensorflow.keras.layers.experimental.preprocessing"
tf_module {
  member {
    name: "CategoryEncoding"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CenterCrop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Discretization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "Hashing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Normalization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "PreprocessingLayer"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "Rescaling"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Resizing"
    mtype: "<class \'type\'>"
  }
}
