path: "tensorflow.keras"
tf_module {
  member {
    name: "Model"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Sequential"
    mtype: "<class \'type\'>"
  }
  member {
    name: "activations"
    mtype: "<class \'module\'>"
  }
  member {
    name: "applications"
    mtype: "<class \'module\'>"
  }
  member {
    name: "backend"
    mtype: "<class \'module\'>"
  }
  member {
    name: "callbacks"
    mtype: "<class \'module\'>"
  }
  member {
    name: "constraints"
    mtype: "<class \'module\'>"
  }
  member {
    name: "datasets"
    mtype: "<class \'module\'>"
  }
  member {
    name: "estimator"
    mtype: "<class \'module\'>"
  }
  member {
    name: "experimental"
    mtype: "<class \'module\'>"
  }
  member {
    name: "export"
    mtype: "<class \'module\'>"
  }
  member {
    name: "initializers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "layers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "losses"
    mtype: "<class \'module\'>"
  }
  member {
    name: "metrics"
    mtype: "<class \'module\'>"
  }
  member {
    name: "mixed_precision"
    mtype: "<class \'module\'>"
  }
  member {
    name: "models"
    mtype: "<class \'module\'>"
  }
  member {
    name: "optimizers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "preprocessing"
    mtype: "<class \'module\'>"
  }
  member {
    name: "regularizers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "saving"
    mtype: "<class \'module\'>"
  }
  member {
    name: "utils"
    mtype: "<class \'module\'>"
  }
  member_method {
    name: "Input"
    argspec: "args=[\'shape\', \'batch_size\', \'name\', \'dtype\', \'sparse\', \'tensor\', \'ragged\', \'type_spec\', \'optional\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'False\'], "
  }
}
