path: "tensorflow.keras.callbacks"
tf_module {
  member {
    name: "BaseLogger"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CSVLogger"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Callback"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CallbackList"
    mtype: "<class \'type\'>"
  }
  member {
    name: "EarlyStopping"
    mtype: "<class \'type\'>"
  }
  member {
    name: "History"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LambdaCallback"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LearningRateScheduler"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ModelCheckpoint"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ProgbarLogger"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ReduceLROnPlateau"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RemoteMonitor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SidecarEvaluatorModelExport"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TensorBoard"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TerminateOnNaN"
    mtype: "<class \'type\'>"
  }
  member {
    name: "experimental"
    mtype: "<class \'module\'>"
  }
}
