path: "tensorflow.keras.layers"
tf_module {
  member {
    name: "AbstractRNNCell"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Activation"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ActivityRegularization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Add"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AdditiveAttention"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AlphaDropout"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Attention"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Average"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AveragePooling1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AveragePooling2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AveragePooling3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AvgPool1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AvgPool2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AvgPool3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "BatchNormalization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Bidirectional"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CategoryEncoding"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CenterCrop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Concatenate"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv1DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv2DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Conv3DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ConvLSTM1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ConvLSTM2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ConvLSTM3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution1DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution2DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Convolution3DTranspose"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Cropping1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Cropping2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Cropping3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Dense"
    mtype: "<class \'type\'>"
  }
  member {
    name: "DenseFeatures"
    mtype: "<class \'type\'>"
  }
  member {
    name: "DepthwiseConv1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "DepthwiseConv2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Discretization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "Dot"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Dropout"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ELU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "EinsumDense"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Embedding"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Flatten"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GRU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GRUCell"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GaussianDropout"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GaussianNoise"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAveragePooling1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAveragePooling2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAveragePooling3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAvgPool1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAvgPool2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalAvgPool3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPool1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPool2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPool3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPooling1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPooling2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GlobalMaxPooling3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "GroupNormalization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "HashedCrossing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Hashing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Identity"
    mtype: "<class \'type\'>"
  }
  member {
    name: "InputLayer"
    mtype: "<class \'type\'>"
  }
  member {
    name: "InputSpec"
    mtype: "<class \'type\'>"
  }
  member {
    name: "IntegerLookup"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "LSTM"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LSTMCell"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Lambda"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Layer"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LayerNormalization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LeakyReLU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LocallyConnected1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "LocallyConnected2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Masking"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPool1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPool2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPool3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPooling1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPooling2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MaxPooling3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Maximum"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Minimum"
    mtype: "<class \'type\'>"
  }
  member {
    name: "MultiHeadAttention"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Multiply"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Normalization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "PReLU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Permute"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RNN"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomBrightness"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomContrast"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomCrop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomFlip"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomHeight"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomRotation"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomTranslation"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomWidth"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomZoom"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ReLU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RepeatVector"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Rescaling"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Reshape"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Resizing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SeparableConv1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SeparableConv2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SeparableConvolution1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SeparableConvolution2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SimpleRNN"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SimpleRNNCell"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Softmax"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SpatialDropout1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SpatialDropout2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SpatialDropout3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SpectralNormalization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "StackedRNNCells"
    mtype: "<class \'type\'>"
  }
  member {
    name: "StringLookup"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "Subtract"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TextVectorization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "ThresholdedReLU"
    mtype: "<class \'type\'>"
  }
  member {
    name: "TimeDistributed"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UnitNormalization"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UpSampling1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UpSampling2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "UpSampling3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Wrapper"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ZeroPadding1D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ZeroPadding2D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "ZeroPadding3D"
    mtype: "<class \'type\'>"
  }
  member {
    name: "experimental"
    mtype: "<class \'module\'>"
  }
  member_method {
    name: "Input"
    argspec: "args=[\'shape\', \'batch_size\', \'name\', \'dtype\', \'sparse\', \'tensor\', \'ragged\', \'type_spec\', \'optional\'], varargs=None, keywords=kwargs, defaults=[\'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'None\', \'False\'], "
  }
  member_method {
    name: "add"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "average"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "concatenate"
    argspec: "args=[\'inputs\', \'axis\'], varargs=None, keywords=kwargs, defaults=[\'-1\'], "
  }
  member_method {
    name: "deserialize"
    argspec: "args=[\'config\', \'custom_objects\', \'use_legacy_format\'], varargs=None, keywords=None, defaults=[\'None\', \'False\'], "
  }
  member_method {
    name: "dot"
    argspec: "args=[\'inputs\', \'axes\', \'normalize\'], varargs=None, keywords=kwargs, defaults=[\'False\'], "
  }
  member_method {
    name: "maximum"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "minimum"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "multiply"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "serialize"
    argspec: "args=[\'layer\', \'use_legacy_format\'], varargs=None, keywords=None, defaults=[\'False\'], "
  }
  member_method {
    name: "subtract"
    argspec: "args=[\'inputs\'], varargs=None, keywords=kwargs, defaults=None"
  }
}
