path: "tensorflow.keras.__internal__"
tf_module {
  member {
    name: "KerasTensor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RaggedKerasTensor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SparseKerasTensor"
    mtype: "<class \'type\'>"
  }
  member {
    name: "backend"
    mtype: "<class \'module\'>"
  }
  member {
    name: "layers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "losses"
    mtype: "<class \'module\'>"
  }
  member {
    name: "models"
    mtype: "<class \'module\'>"
  }
  member {
    name: "optimizers"
    mtype: "<class \'module\'>"
  }
  member {
    name: "utils"
    mtype: "<class \'module\'>"
  }
  member_method {
    name: "apply_name_scope_on_model_declaration"
    argspec: "args=[\'enable\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "enable_unsafe_deserialization"
    argspec: "args=[], varargs=None, keywords=None, defaults=None"
  }
}
