path: "tensorflow.keras.layers.experimental.preprocessing"
tf_module {
  member {
    name: "CategoryEncoding"
    mtype: "<class \'type\'>"
  }
  member {
    name: "CenterCrop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Discretization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "HashedCrossing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Hashing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "IntegerLookup"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "Normalization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "PreprocessingLayer"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "RandomContrast"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomCrop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomFlip"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomHeight"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomRotation"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomTranslation"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomWidth"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RandomZoom"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Rescaling"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Resizing"
    mtype: "<class \'type\'>"
  }
  member {
    name: "StringLookup"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "TextVectorization"
    mtype: "<class \'abc.ABCMeta\'>"
  }
}
