path: "tensorflow.keras.dtensor.experimental.optimizers"
tf_module {
  member {
    name: "Adadelta"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Adagrad"
    mtype: "<class \'type\'>"
  }
  member {
    name: "Adam"
    mtype: "<class \'type\'>"
  }
  member {
    name: "AdamW"
    mtype: "<class \'type\'>"
  }
  member {
    name: "RMSprop"
    mtype: "<class \'type\'>"
  }
  member {
    name: "SGD"
    mtype: "<class \'type\'>"
  }
}
