path: "tensorflow.keras.mixed_precision.LossScaleOptimizer"
tf_class {
  is_instance: "<class \'tf_keras.mixed_precision.loss_scale_optimizer.BaseLossScaleOptimizer\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "dynamic"
    mtype: "<class \'property\'>"
  }
  member {
    name: "dynamic_counter"
    mtype: "<class \'property\'>"
  }
  member {
    name: "dynamic_growth_steps"
    mtype: "<class \'property\'>"
  }
  member {
    name: "initial_scale"
    mtype: "<class \'property\'>"
  }
  member {
    name: "inner_optimizer"
    mtype: "<class \'property\'>"
  }
  member {
    name: "loss_scale"
    mtype: "<class \'property\'>"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "get_scaled_loss"
    argspec: "args=[\'self\', \'loss\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "get_unscaled_gradients"
    argspec: "args=[\'self\', \'grads\'], varargs=None, keywords=None, defaults=None"
  }
}
