path: "tensorflow.keras.__internal__.layers"
tf_module {
  member {
    name: "BaseDenseAttention"
    mtype: "<class \'type\'>"
  }
  member {
    name: "BaseRandomLayer"
    mtype: "<class \'type\'>"
  }
}
