path: "tensorflow.keras.dtensor.experimental"
tf_module {
  member {
    name: "LayoutMap"
    mtype: "<class \'abc.ABCMeta\'>"
  }
  member {
    name: "optimizers"
    mtype: "<class \'module\'>"
  }
}
